import React from "react";

import { S3Client, ListObjectsV2Command, type ListObjectsV2CommandOutput } from "@aws-sdk/client-s3";
import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

const HomeMovies: NextPage<{bucketContents: ListObjectsV2CommandOutput['Contents']}> = ({bucketContents}) => {



  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <video src="https://t3-stream.s3.amazonaws.com/2021-09-22T21:00:00.000Z.mp4" controls></video>


      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Home Movies
          </h1>

          {bucketContents && bucketContents?.length > 0 ? 
            bucketContents.map((object) => (<div key={object.Key}>{object.Key}</div>)) : 
            <div>No movies found</div>
          }
        </div>
      </main>
    </>
  );
};

export async function getStaticProps() {
  const {AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_BUCKET_NAME} = process.env;

  const s3 = new S3Client({ region: "us-east-1", credentials: {accessKeyId: AWS_ACCESS_KEY_ID as string, secretAccessKey: AWS_SECRET_ACCESS_KEY as string} });

  const result = await s3.send(new ListObjectsV2Command({Bucket: AWS_BUCKET_NAME as string }));

  console.log(result)

  return {props: {bucketContents: JSON.parse(JSON.stringify(result.Contents))}}
}

export default HomeMovies;
